# Bordes de paneles en blanco
set -g pane-border-style fg=white
set -g pane-active-border-style fg=white,bold

# Forzar colores: fondo azul, texto amarillo brillante
set -g status-style "bg=black,fg=yellow,bold"

# Refresco cada 5 segundos
set -g status-interval 5

# Ocultar lista de ventanas
set -g window-status-format ""
set -g window-status-current-format ""

# Barra izquierda: solo nombre de sesión
set -g status-left "#[fg=red]⫻#[fg=green]⫻#[fg=blue]⫻ #[bold,fg=yellow] AMSTRAD CPC READY "
# Barra derecha: solo hora
set -g status-right "%H:%M:%S"

setw -g window-style "bg=default,fg=white"
setw -g window-active-style "bg=default,fg=white"